services:
  strapi:
    image: naskio/strapi
    container_name: strapi-app
    restart: always
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    ports:
      - "1337:1337"
    volumes:
      - strapi_data:/srv/app

volumes:
  strapi_data: